"""Generate styling/matrices.md -- the wardrobe as browsable matrices."""
import itertools
import os

import rank as R

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'matrices.md')

SHORT_B = {
    '0zrthxzlt': 'Lounge', 'blk-shorts': 'Blk Shrt', 'beige-shorts': 'Bge Shrt',
    'b3': 'Denim', 'navy-linen-shorts': 'Nvy Shrt', 'b5': 'Camel',
    'b2': 'Bge Linen', 'brown-chinos': 'Dk Brown', 'b1': 'Pleated',
}


def band(v):
    if v is None:
        return '  -  '
    if v >= 84:
        return f'**{v:.0f}**'
    return f'{v:.0f}'


def main():
    tops, bottoms, shoes = R.load()
    sandal = [s for s in shoes if s['id'] == 'cork-sandals'][0]
    L = []
    A = L.append

    A('# Wardrobe matrices')
    A('')
    A('Generated by `styling/matrix.py`. Scores from the rubric in '
      '`styling/scoring-method.md`.')
    A('')

    # ---------------------------------------------------------------- why 2D
    A('## Why one 2D matrix is enough')
    A('')
    A('An outfit is three choices, so the full picture is a **cube**: '
      '14 tops x 9 bottoms x 3 shoes = 378 cells. You cannot draw a cube on a '
      'page. The usual options are:')
    A('')
    A('| Option | What it looks like | Cost |')
    A('|---|---|---|')
    A('| **Slice it** | 3 separate 14x9 grids, one per shoe | Nothing lost, but 3 grids to compare by eye |')
    A('| **Collapse it** | 1 grid of 14x9, each cell = best shoe | Hides the shoe choice |')
    A('| **Split it** | tops x bottoms grid + a separate bottoms x shoes grid | Only works if the shoe does not interact |')
    A('')
    A('Which one is right is not a matter of taste — it depends on whether the '
      'shoe **interacts** with the top and bottom, or just shifts everything by '
      'a constant. That is measurable, so I measured it.')
    A('')
    A('```mermaid')
    A('flowchart LR')
    A('    C["CUBE<br/>14 x 9 x 3<br/>378 cells"] --> Q{"Does the shoe<br/>change which<br/>top+bottom wins?"}')
    A('    Q -->|"Yes, it interacts"| S["Must slice:<br/>3 separate grids"]')
    A('    Q -->|"No, constant offset"| F["Can split:<br/>1 grid + 1 short list"]')
    A('    F --> A1["TOPS x BOTTOMS<br/>14 x 9 = 126 cells"]')
    A('    F --> A2["SHOE ADJUSTMENT<br/>3 numbers"]')
    A('    F --> A3["FEASIBILITY<br/>which shoe reaches<br/>which formality"]')
    A('```')
    A('')

    raw = {(t['id'], b['id'], s['id']): R.score(t, b, s)[0]
           for t, b, s in itertools.product(tops, bottoms, shoes)}
    flips = sum(1 for t in tops for b in bottoms
                if max(shoes, key=lambda s: raw[(t['id'], b['id'], s['id'])])['id']
                != 'cork-sandals')
    A('**Measured result:** swapping the shoe moves every cell by almost exactly '
      'the same amount, and the cork sandals win in **'
      f'{126 - flips} of 126** cells:')
    A('')
    A('| Shoe | Effect on score | Varies by |')
    A('|---|---|---|')
    for s in shoes:
        d = [raw[(t['id'], b['id'], s['id'])] - raw[(t['id'], b['id'], 'cork-sandals')]
             for t in tops for b in bottoms]
        A(f"| {s['title']} | {sum(d)/len(d):+.1f} | "
          f"only {max(d)-min(d):.1f} pts across all 126 cells |")
    A('')
    A('A shift that constant is not a real third dimension. The shoe **does not '
      'change which outfit is better** — it changes how good all of them are, '
      'by the same amount. So: one 2D grid, plus three numbers.')
    A('')
    A('The shoe only genuinely matters in one place, and it is not the score — '
      'it is **reach**. See the feasibility grid at the bottom.')
    A('')

    # ------------------------------------------------------- main 2D matrix
    A('## Matrix 1 — tops x bottoms')
    A('')
    A('Score assumes **cork sandals**. For the other two, subtract ~9 (Onitsuka) '
      'or ~10 (Sambas). `--` means the pairing is incoherent at any formality. '
      'Bold = 84+.')
    A('')
    hdr = '| Top \\ Bottom | ' + ' | '.join(SHORT_B[b['id']] for b in bottoms) + ' | best |'
    A(hdr)
    A('|' + '---|' * (len(bottoms) + 2))
    rows = []
    for t in tops:
        cells, vals = [], []
        for b in bottoms:
            if not R.coherent(t, b, sandal):
                cells.append('--')
                continue
            v = raw[(t['id'], b['id'], sandal['id'])]
            cells.append(band(v))
            vals.append(v)
        rows.append((max(vals) if vals else 0, t['title'], cells))
    for best, title, cells in sorted(rows, reverse=True):
        A(f"| {title} | " + ' | '.join(cells) + f" | {best:.0f} |")
    A('')
    colbest = []
    for b in bottoms:
        vals = [raw[(t['id'], b['id'], sandal['id'])] for t in tops
                if R.coherent(t, b, sandal)]
        colbest.append(max(vals) if vals else 0)
    A('| best | ' + ' | '.join(f'{v:.0f}' for v in colbest) + ' | |')
    A('')
    A('### The two empty lines mean opposite things')
    A('')
    A('The Pleated **column** and the White Formal **row** are both all `--`, '
      'but for completely different reasons, and it would be easy to draw the '
      'wrong conclusion:')
    A('')
    A('- **White Formal row — genuinely dead.** Its formality floor is 0.55. '
      'No bottom *and no shoe* you own reaches that. It is empty in all three '
      'slices of the cube. Leave it home.')
    A('- **Pleated column — an artifact of this slice only.** The pants are '
      'fine; they just cannot be worn with the sandals this grid assumes '
      '(sandals cap at 0.40, pleats start at 0.45). Swap to a sneaker and the '
      'column fills in completely:')
    A('')
    onitsuka = [s for s in shoes if s['id'] == 'xfgc52qo3'][0]
    pleated = [b for b in bottoms if b['id'] == 'b1'][0]
    pl = sorted(((raw[(t['id'], pleated['id'], onitsuka['id'])], t['title'])
                 for t in tops if R.coherent(t, pleated, onitsuka)), reverse=True)
    A('| Black Pleated + Onitsuka | Score |')
    A('|---|---|')
    for v, title in pl[:5]:
        A(f'| {title} | {v:.0f} |')
    A(f'| ...{len(pl)-6} more | |')
    A(f'| {pl[-1][1]} | {pl[-1][0]:.0f} |')
    A('')
    A('This is the general trap with a collapsed matrix: **an empty cell can '
      'mean "impossible" or it can mean "you are looking at the wrong slice."** '
      'Matrix 2 below is what tells you which.')
    A('')

    # ------------------------------------------------ feasibility / reach
    A('## Matrix 2 — bottoms x shoes (reach, not quality)')
    A('')
    A('This is the only place the shoe earns its own grid. A tick means the '
      'pairing is formality-coherent; the range is how far up it can go.')
    A('')
    A('| Bottom | ' + ' | '.join(s['title'].split(' (')[0] for s in shoes) + ' |')
    A('|' + '---|' * (len(shoes) + 1))
    for b in bottoms:
        cells = []
        for s in shoes:
            lo = max(b['formality'][0], s['formality'][0])
            hi = min(b['formality'][1], s['formality'][1])
            cells.append(f'{lo:.2f}–{hi:.2f}' if lo <= hi else 'x')
        A(f"| {b['title']} | " + ' | '.join(cells) + ' |')
    A('')
    A('Read the right-hand columns: the sneakers are the only way to reach '
      'above **0.40**. That is the entire argument for packing them — not that '
      'they look better, they do not, but that the sandals cannot go there.')
    A('')

    # ---------------------------------------------------------- how to read
    A('## How to read Matrix 1')
    A('')
    A('- **A row that is mostly low** = a top that is hard to use. '
      'Look at Black Crew-neck and Forest Corduroy.')
    A('- **A column that is mostly high** = a bottom worth packing. '
      'Beige Linen Pants and Beige Shorts carry the wardrobe.')
    A('- **`--` in a cell** = not a taste judgement, a hard incoherence: the two '
      'pieces have no formality level at which they both work.')
    A('- **The `best` column** is the ceiling for that top. A top whose best is '
      'under 70 is not worth the suitcase space.')
    A('')

    with open(OUT, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
